services:
  - type: web
    name: certifsure-laravel
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://certifsure-laravel.onrender.com

      # Configuration PostgreSQL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1mi6r6mcj7s73adk560-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: certiff_db
      - key: DB_USERNAME
        value: certiff_db_user
      - key: DB_PASSWORD
        value: SqJt5N9kfjwY07VfOpHHMAZJ0LLSyf38
